apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch 
metadata:
  name: elasticsearch-cs
spec:
  version: 8.3.2
  nodeSets:
  - name: nodes
    count: 1
    config:
      node.roles: ["master", "data"]
      node.store.allow_mmap: false 
    podTemplate:
      spec:
        volumes: 
        - name: elasticsearch-data
          emptyDir:
             medium: Memory           
        containers:
          - name: elasticsearch
            volumeMounts:
             - mountPath: /octodet-memory
               name: elasticsearch-data
            readinessProbe:
              exec:
                command:
                - bash
                - -c
                - /mnt/elastic-internal/scripts/readiness-probe-script.sh
              failureThreshold: 3
              initialDelaySeconds: 10
              periodSeconds: 30
              successThreshold: 1
              timeoutSeconds: 30
            env:
            - name: READINESS_PROBE_TIMEOUT
              value: "60"   

---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-cs
spec:
  version: 8.3.2
  count: 1
  elasticsearchRef:
    name: elasticsearch-cs
